apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: stockdb
  name: stockdb
spec:
  ports:
    - name: "27018"
      port: 27018
      targetPort: 27018
  selector:
    io.kompose.service: stockdb
status:
  loadBalancer: {}
