apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\tilef\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: product
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\tilef\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/testmicroservice-main: "true"
        io.kompose.service: product
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings:ConnectionString
              value: mongodb://productdb:27017
          image: product
          name: product
          ports:
            - containerPort: 8080
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
